[ (error (fun (con integer) (con integer))) (con integer 1) ]