An error has occurred:
The machine terminated because of an error, either from a built-in function or from an explicit use of 'error'.
Caused by: error

Trace:
entering func:test/CallTrace/Spec.hs:69:1-69:4
entering nestedLinear2:test/CallTrace/Spec.hs:63:1-63:13
entering nestedLinear3:test/CallTrace/Spec.hs:64:1-64:13
entering nestedLinear4:test/CallTrace/Spec.hs:65:1-65:13
entering error