An error has occurred:
The machine terminated because of an error, either from a built-in function or from an explicit use of 'error'.
Caused by: error

Trace:
entering func:test/CallTrace/Spec.hs:69:1-69:4
entering $cmyClassFunc:test/CallTrace/Spec.hs:90:3-90:13
entering error